config/routes.rb
Nakedplus::Application.routes.draw do
  root "pages#home"
  get "products" => "pages#products"
  get "signup" => "pages#signup"
  get "support" => "pages#support"
  get "about" => "pages#about"
  get "login" => "pages#login"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def products
  end

  def signup
  end

  def support
  end

  def about
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
      		<span class="icon-bar"></span>
      		<span class="icon-bar"></span>
    	</button>
    	<a class="navbar-brand" href="#">The Internet Company</a>
  	</div>

  	<!-- Collect the nav links, forms, and other content for toggling -->
  	<div class="collapse navbar-collapse navbar-ex1-collapse">
    	<ul class="nav navbar-nav navbar-right">
      		<li><%= link_to "Home", root_path %></li>
      		<li><%= link_to "Products", products_path %></li> 
      		<li><%= link_to "Signup", signup_path %></li>
			<li><%= link_to "Support", support_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Log in", login_path %></li>
    	</ul>
  	</div>
  	<!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nakedplus</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>We probably exist</p>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>The Internet Company</h1>
	<p>Technology + Us + You = The Future.</p>
</div>

app/views/pages/login.html.erb
<h1>Log in</h1>
<p>Submit a support ticket etc here</p>

app/views/pages/products.html.erb
<h1>Products</h1>
<p>We have them</p>

app/views/pages/signup.html.erb
<h1>Sign up</h1>
<p>Get some of our cool stuff</p>

app/views/pages/support.html.erb
<h1>Support</h1>
<p>This is where we fix your things</p>